Implementing DiffieHellman Key Exchange
Cryptonite-team/Rainbow pull request #7
Opened 2017-11-06 04:05 UTC by Han3l

Diffie-Hellman Key Exchange Algorithm 구현.
Diffie-Hellman.h는 Diffie-Hellman Key Exchange Algorithm이 구현되어 있습니다.

* uint64_t GenerateExchangeData(uint64_t pModule, uint64_t gModule)
* uint64_t GenerateExchangeKey(uint64_t responseData)

main.cpp는 Diffie-Hellman.h를 테스트하기 위해 제작되었습니다.

2017-11-16 12:46 UTC, utilForever requested changes
고쳐야 할 부분을 표시했고, 궁금한 점도 같이 달아뒀어.
확인하고 답변 달아줘. 작업하느라 고생했어. :^)

2017-11-16 12:46 UTC, utilForever commented on DiffieHellman/Diffie-Hellman.h
> +#pragma once
```#ifndef ~ #define ~ #endif```를 했다면 없어도 됨

2017-11-16 12:46 UTC, utilForever commented on DiffieHellman/Diffie-Hellman.h
> +    void setPModule(uint64_t _pModule)
메서드 이름은 대문자로 시작 : ```SetPModule```, 인수 앞에 ```_``` 빼도 괜찮을 듯

2017-11-16 12:46 UTC, utilForever commented on DiffieHellman/Diffie-Hellman.h
> +    bool Prime(uint64_t _pModule)
함수 이름을 ```IsPrime```으로 변경, 인수 앞에 ```_``` 빼도 괜찮을 듯

2017-11-16 12:46 UTC, utilForever commented on DiffieHellman/Diffie-Hellman.h
> +    void setModule(uint64_t _module)
메서드 이름은 대문자로 시작 : ```SetModule```, 인수 앞에 ```_``` 빼도 괜찮을 듯

2017-11-16 12:46 UTC, utilForever commented on DiffieHellman/Diffie-Hellman.h
> +        uint64_t data = (uint64_t) pow(module, randModule) % pModule;
타입 변환은 ```static_cast``` 사용 권장 (NRVO 적용)

2017-11-16 12:46 UTC, utilForever commented on DiffieHellman/Diffie-Hellman.h
> +    void remove()
메서드 이름은 대문자로 시작 : ```Remove```
그리고 ```Remove```라는 이름보다는 ```Clear```가 좋지 않을까 싶음.

2017-11-16 12:46 UTC, utilForever commented on DiffieHellman/Diffie-Hellman.h
> +    uint64_t getPModule()
메서드 이름은 대문자로 시작 : ```GetPModule```

2017-11-16 12:46 UTC, utilForever commented on DiffieHellman/Diffie-Hellman.h
> +    uint64_t pModule;
멤버 변수 이름 앞에는 ```m_```를 붙일 것 → ```m_pModule;```
근데 ```m_pModule```이랑 ```m_module```이랑 뭐가 다른건지?
```p```가 붙었다는건 포인터라는 소린데 그게 아니라면 이름을 명확하게 바꾸는게 좋을 듯.

2017-11-16 12:46 UTC, utilForever commented on DiffieHellman/Diffie-Hellman.h
> +    uint64_t module;
멤버 변수 이름 앞에는 ```m_```를 붙일 것 → ```m_module;```

2017-11-16 12:46 UTC, utilForever commented on DiffieHellman/Diffie-Hellman.h
> +} util;
전역 변수로 선언하는건가? 싱글턴 패턴을 고려한건지 궁금.

2017-11-16 12:48 UTC, Han3l commented on DiffieHellman/Diffie-Hellman.h
> +    uint64_t pModule;
diffiehellman에서는 p와 g, 그리고 전달 받은 값을 가지고 연산을 하는데, module은 g와 전달 받은 값을 저장하기 위한 변수이고 pModule은 p를 저장하기 위한 변수인데 네이밍이 지금보니 이상하긴 하네

2017-11-16 12:49 UTC, Han3l commented on DiffieHellman/Diffie-Hellman.h
> +} util;
계속해서 만들 필요가 없을 뿐더러 값을 초기화하기 전까지 저장해두고 싶어서 이렇게 했는데 다른 좋은 방법이 있을까? 싱글턴 패턴으로 한다면 더 좋으려나

2017-11-16 12:49 UTC, Han3l commented on DiffieHellman/Diffie-Hellman.h
> +#pragma once
실수

2017-11-16 12:50 UTC, Han3l commented on DiffieHellman/Diffie-Hellman.h
> +    void setPModule(uint64_t _pModule)
메서드 이름을 대문자로 안한 것들 모두 실수 (한동한 자바하느라 앞에 소문자를 쓰는게 익숙해진듯)

2017-11-16 12:59 UTC, utilForever commented on DiffieHellman/Diffie-Hellman.h
> +} util;
밑에 두 함수 때문에 그런 거 같은데 그러면 두 함수를 클래스 메서드로 만들면 되지 않아?

2017-11-16 12:59 UTC, Han3l commented
아 그리고 uint64_t는 2**64 - 1까지라 현재 boost library로 uint1024_t로 바꾸는 작업을 하고 있는데 일부 오류가 있어서 그 부분에서는 도움을 좀 받고 싶어

2017-11-16 13:00 UTC, ys9-4 commented on DiffieHellman/Diffie-Hellman.h
> +} util;
사용자가 객체를 안만들기를 원해서 클래스 메서드로 안만드는 방향으로 설계했는데 이상한가?

2017-11-16 13:03 UTC, utilForever commented on DiffieHellman/Diffie-Hellman.h
> +} util;
음 무슨 말인지 이해했음, 그러면 싱글턴으로 만드는게 어떨까 싶음.
함수 내부에서 개체가 nullptr이면 생성해주도록 하면 되지 않을까?
그리고 한가지 빼먹었는데, 헤더 파일과 구현 파일은 분리해줘.

2017-11-16 13:08 UTC, Han3l commented on DiffieHellman/Diffie-Hellman.h
> +} util;
싱글턴 패턴을 쓰든, 전역 변수를 사용하던 사용자 입장에서는 util 객체를 접근할 수 있으니 생각을 좀더 해봐야 될 것 같고 uint64_t는 이제 boost library 이용해서 바꿔야 될듯

2017-11-16 13:10 UTC, utilForever commented
boost를 달기엔 너무 무거워서 따로 하나 구현하는게 나을 듯.
일단은 uint64_t로 작업해서 올려줘.

2017-11-21 05:27 UTC, 5unkn0wn approved these changes
굳

2017-11-21 14:48 UTC, utilForever approved these changes
피드백한 부분의 수정 사항 반영 확인했어.
고생많았다. 이상 완료~!

2017-11-21 14:48 UTC, merged